## This is the main plugin configuration file
#This is your bot token
DISCORD_TOKEN: ""
#This is the discord guild ID.  Get this while in dev mode by right clicking the discord server and selecting "Copy ID"
DISCORD_ID: ""
BOT_CLIENT_ID: ""
#Discord roll name for adding perms.  Only members with this roll will be able to interact with the bot
ROLE: "Staff"
#Application Channel ID's
appPending: "967938193737527316"
appAccepted: "967938282514153482"
appDenied: "967938335031066634"


## MySQL database connection info
## database:
host:  # host of your database
port:  # default port for MariaDB and MySQL
database:  # name of your database. A database server can contain multiple databases
user:
password: