## This is the main plugin configuration file

DISCORD_TOKEN: "NzM1NjU5MTMxODEzNDk0ODc1.Xxjd9A.ttC54q9JhB7vMHoEMnRRWoNo6CQ"
BOT_CLIENT_ID: "735659131813494875"
#Discord roll name for adding perms.  Only members with this roll will be able to interact with the bot
ROLE: "Staff"


## MySQL database connection info
## database:
host: dynanode.bloom.host # host of your database
port: 3306 # default port for MariaDB and MySQL
database: s15445_whitelist # name of your database. A database server can contain multiple databases
user: u15445_6WTcwtustf
password: 8mejQK^gEt5HHsAoY=L!nhia