## This is the main plugin configuration file
#This is your bot token
discordToken:
#This is the discord guild ID.  Get this while in dev mode by right-clicking the discord server and selecting "Copy ID"
discordId:
botClientId:
#Discord roll ID's for adding perms.  These roles are required for bot permissions, however, they can be changed to anything you want.
##Members with this role can use all discord commands
staffRole:
##Only members with this role can use the apply command
appRole:

##CHANNELS##
#Application Channel ID's
appPending:
appAccepted:
appDenied:
#Welcome Channel ID
welcomeChannel:
#Howdy Channel ID
howdyChannel:
#rules Channel ID
rulesChannel:
#Set whether you want Heimdall to welcome members to your server (default: true)

##CATEGORIES##
staffCategory:

#Set whether you want Heimdall to welcome members to your server (default: true)
welcomeMessages: false


## MySQL database connection info
## database:
host:  # host of your database
port:  # default port for MariaDB and MySQL
database:  # name of your database. A database server can contain multiple databases
user:
password: