## This is the main plugin configuration file
#DEBUG logging
debug: false
#This is your bot token
discordToken:
#This is the discord guild ID.  Get this while in dev mode by right-clicking the discord server and selecting "Copy ID"
discordId:
botClientId:
#Discord roll ID's for adding perms.  These roles are required for bot permissions, however, they can be changed to anything you want.
##Members with this role can use all discord commands
staffRole:

## MySQL database connection info
## database:
host:  # host of your database
port:  # default port for MariaDB and MySQL
database:  # name of your database. A database server can contain multiple databases
user:
password: