## This is the main plugin configuration file
#This is your bot token
DISCORD_TOKEN: ""
#This is the discord guild ID.  Get this while in dev mode by right clicking the discord server and selecting "Copy ID"
DISCORD_ID: ""
BOT_CLIENT_ID: ""
#Discord roll name for adding perms.  These roles are required for bot permissions, however, they can be changed to anything you want.
STAFF_ROLE: "Staff"  ##Members with this role can use all discord commands
APPLICANT_ROLE: "Applicant"   ##Only members with this role can use the apply command
#Application Channel names, these can be changed to whatever channel(s) you've created in your discord, they just can't be blank.

##CHANNELS##
appPending: "pending-applications"
appAccepted: "accepted-applications"
appDenied: "denied-applications"
#Welcome Channel name
welcomeChannel: "welcome"
#Howdy Channel name
howdyChannel: "howdy"
#rules Channel name
rulesChannel: "rules"
#Set whether you want Heimdall to welcome members to your server (default: true)

##CATEGORIES##
staffCategory: "═══════  Staff   ═══════"
WelcomeMessages: true




## MySQL database connection info
## database:
host:  # host of your database
port:  # default port for MariaDB and MySQL
database:  # name of your database. A database server can contain multiple databases
user:
password: