########################
##  Main Application  ##
########################

# Questions format  #
# Questions:        # All questions are numbered under this questions category
#   1:              # This is the question number
#     Q:            # Put your main question here
#       type:       # There are four different question types:
#                   # number (for number responses), short (for short responses), long (for long responses), choice (for responses like yes/no or other defined response choices)
#       options:    # This is required if you put choice as your question type.  You can put any number of options in square brackets separated by a comma.
#     SQ:           # This is a special option for a follow-up question.  Put your sub question here.
#       type:       # The type and options follow the same guidelines as above
#       options:    #

Questions:
  1:
    Q: How old are you?
      type: number

  2:
    Q: Where are you from / what is your timezone?
      type: short

  3:
    Q: Do you plan on using voice chat?
      type: choice
      options: [ yes, no ]

  4:
    Q: Do you use in game chat regularly?
      type: choice
      options: [ yes, no ]

  5:
    Q: How did you find us? If through a friend please state their name.
      type: short

  6:
    Q: Tell us a little about yourself. (Dont just write "I like Minecraft" tell us more! We want to get to know you!)
      type: long

  7:
    Q: What is your main focus here at Bifrost? (Survival, Minigames, Creative, other?)
      type: choice
      options: [ Survival, Mini-Games, Creative, Other ]
    SQ: Please describe the other things you want to focus on
      type: short

  8:
    Q: What are some ideas of builds that you would like to create?
      type: short

  9:
    Q: Do you have any other questions, concerns or anything extra you'd like to add?
      type: short

  10:
    Q: Did you read the rules?
      type: choice
      options: [ yes, no ]












