#This is the main plugin configuration file
#debug mode
debug: false
#Hardcore server mode: If this is enabled players will be temp banned for a number of hours.
hardcore: false #[default false]
tempBan: 12 #[default 12]
firstRun: true

#Server Name (REQUIRED!)
server: default

#MySQL database connection info
database:
  host:  # host of your database
  port:  # default port for MariaDB and MySQL
  database:  # name of your database. A database server can contain multiple databases
  user:
  password: