#This is the main plugin configuration file
#debug mode
debug: false
firstRun: true

#Server Name (REQUIRED!)
server: default

#MySQL database connection info
database:
  host:  # host of your database
  port:  # default port for MariaDB and MySQL
  database:  # name of your database. A database server can contain multiple databases
  user:
  password: